apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ template "rasa-x.rasa-x.configuration-files" . }}
  labels:
    {{ include "rasa-x.labels" . | nindent 4 }}
data:
  environments: |
    rasa:
    {{- range .Values.rasa.versions }}
      {{ .rasaEnvironment }}:
        url: "{{ $.Values.rasa.scheme }}://{{ include "rasa-x.fullname" $ }}-{{ .serviceName }}.{{ $.Release.Namespace }}.svc:{{ $.Values.rasa.port }}"
        token: ${RASA_TOKEN}
    {{- end }}
