apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ template "rasa-x.rasa-x.configuration-files" . }}
  labels:
    {{ include "rasa-x.labels" . | nindent 4 }}
data:
  environments: |
    rasa:
    {{- range .$version, $version_config := .Values.rasa.versions }}
      {{ .$version_config.rasaEnvironment }}:
        url: "{{ .Values.rasa.scheme }}://{{ include "rasa-x.fullname" . }}-{{ $version_config.serviceName }}.{{ .Release.Namespace }}.svc:{{ .Values.rasa.port }}"
        token: ${RASA_TOKEN}
    {{ end }}
